#!/usr/bin/env python3
"""Regenerate the arm-vs-chassis self-collision pairs, one file per tool.

The arm's *internal* matrix comes from mod101 (`mod101_arm_srdf` emits
`mod101_collisions_<tool>`), and the arm's geometry is the same whether or not
it is bolted to a robot. What no standalone arm config can know is which pairs
involving the *chassis* can never collide — and on base101 that matters a lot:
the arm reaches ~525 mm from a turret 186 mm up, so the lidar, the Orin, the
camera and the bumpers are all inside its envelope.

So this generates the complement: every disabled pair with at least one chassis
link. Arm-vs-arm pairs are dropped, because mod101 already supplies them and
duplicating them would just bloat the SRDF.

Like mod101's tools/gen_collision_matrix.py (which this mirrors), the output is
build-dependent: the rail lengths move the arm's reach, so a pair that never
collides on a short arm may collide on a long one. Regenerate whenever the
configurator changes the arm — its Save does this automatically.

    python3 scripts/gen_collision_matrix.py                   # all tools
    python3 scripts/gen_collision_matrix.py --tool jaws       # just one
    python3 scripts/gen_collision_matrix.py --trials 4000000  # more thorough

A NOTE ON TRIALS. "Never colliding" is decided by random sampling, so it is a
statistical claim, not a proof — and disabling a pair that *can* collide is the
dangerous direction. Measured on this robot (jaws, 140/140 mm rails):

    trials      pairs disabled
      10,000    856
     200,000    853   (10k wrongly disabled jaws_moving vs both back standoffs
                       and the back-left wheel)
     500,000    851
   1,000,000    850
   2,000,000    849

It is still shedding roughly one pair per doubling at 2M: those are pairs that
only touch in a vanishingly small corner of joint space. The default below is
chosen to be past the knee, not to be exhaustive. If you add reach (longer
rails, a big mount) re-run with more trials and diff the output.

Needs a sourced ROS 2 Jazzy, the mod101 underlay, and a built workspace.
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / 'config' / 'collisions'
TOOLS = ('jaws', 'parallel', 'pincopen', 'none')

# The composed robot: chassis + arm.
URDF_XACRO = (ROOT.parents[0] / 'base101_arm_description' / 'urdf' / 'base101_arm.xacro')

# Everything the mod101 macro contributes is prefixed; everything else is chassis.
ARM_PREFIX = 'arm_'

HEADER = """<?xml version="1.0"?>
<!--
  GENERATED by base101_arm_moveit_config/scripts/gen_collision_matrix.py
  — do not edit by hand.

  tool={tool}  {build}
  {npairs} chassis-involving pairs disabled ({ndefault} adjacent/always,
  {nnever} never-colliding over {trials} random samples), out of {ntotal}
  pairs in the composed robot. "Never" is statistical — see the generator's
  docstring for the trials-vs-pairs convergence on this robot.

  Arm-vs-arm pairs are NOT here: mod101_collisions_{tool} supplies those, and
  the arm's internal geometry does not change by being mounted. Regenerate
  after any configurator change; see the script's docstring.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="base101_arm_collisions_{tool}" params="">
"""

FOOTER = """</xacro:macro>
</robot>
"""


def mod101_build_args():
    """The four build params as the mod101 configurator last saved them."""
    from ament_index_python.packages import get_package_share_directory
    cfg = Path(get_package_share_directory('mod101_description')) / 'urdf' / 'mod101_config.xacro'
    args = dict(re.findall(
        r'<xacro:arg\s+name="(shoulder_ext_length|elbow_ext_length|'
        r'shoulder_mount|elbow_mount)"\s+default="([^"]+)"', cfg.read_text()))
    missing = {'shoulder_ext_length', 'elbow_ext_length',
               'shoulder_mount', 'elbow_mount'} - args.keys()
    if missing:
        sys.exit(f'{cfg}: missing build args {sorted(missing)}')
    return args


def run(cmd, **kw):
    proc = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if proc.returncode != 0:
        sys.exit(f'! {" ".join(cmd)}\n{proc.stdout}\n{proc.stderr}')
    return proc.stdout


def bootstrap_srdf(tool):
    """A minimal SRDF with the group but no disable_collisions.

    collisions_updater needs a valid SRDF to start from, and the real one
    includes the file we are about to write — so build a standalone one rather
    than expanding base101_arm.srdf.xacro, which would be circular.
    """
    return f"""<?xml version="1.0"?>
<robot name="base101_arm">
  <group name="{ARM_PREFIX}arm">
    <chain base_link="{ARM_PREFIX}base_link" tip_link="{ARM_PREFIX}wrist_flange"/>
  </group>
  <virtual_joint name="virtual_joint" type="fixed"
                 parent_frame="world" child_link="base_link"/>
</robot>
"""


def generate(tool, trials, args):
    print(f'==> {tool}', flush=True)
    mappings = [f'{k}:={v}' for k, v in args.items()] + [
        'simulator:=none', 'arm:=true', f'arm_tool:={tool}']

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        urdf, srdf_in, srdf_out = td / 'r.urdf', td / 'in.srdf', td / 'out.srdf'

        urdf_text = run(['xacro', str(URDF_XACRO), *mappings])
        urdf.write_text(urdf_text)
        srdf_in.write_text(bootstrap_srdf(tool))
        nlinks = len(re.findall(r'<link name=', urdf_text))

        run(['ros2', 'run', 'moveit_setup_assistant', 'collisions_updater',
             '--urdf', str(urdf), '--srdf', str(srdf_in),
             '--output', str(srdf_out),
             '--default', '--always', '--trials', str(trials)])

        pairs = re.findall(r'<disable_collisions[^/]*/>', srdf_out.read_text())

    body, counts, kept = [], {'default': 0, 'never': 0, 'always': 0}, 0
    for p in pairs:
        l1 = re.search(r'link1="([^"]*)"', p).group(1)
        l2 = re.search(r'link2="([^"]*)"', p).group(1)
        # mod101 already owns the arm-internal pairs.
        if l1.startswith(ARM_PREFIX) and l2.startswith(ARM_PREFIX):
            continue
        kept += 1
        reason = re.search(r'reason="([^"]*)"', p)
        r = (reason.group(1) if reason else '').lower()
        counts['never' if r == 'never' else
               'always' if r == 'always' else 'default'] += 1
        body.append('  ' + p)

    header = HEADER.format(
        tool=tool,
        build=' '.join(f'{k}={v}' for k, v in args.items()),
        npairs=kept, ntotal=nlinks * (nlinks - 1) // 2,
        ndefault=counts['default'] + counts['always'],
        nnever=counts['never'], trials=trials)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / f'{tool}.srdf.xacro').write_text(
        header + '\n'.join(body) + '\n' + FOOTER)
    print(f'    {kept} chassis pairs disabled of {len(pairs)} total '
          f'({counts["default"] + counts["always"]} adjacent/always, '
          f'{counts["never"]} never)')


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--tool', choices=TOOLS, action='append',
                    help='only this tool (repeatable); default all')
    ap.add_argument('--trials', type=int, default=1000000,
                    help='random samples for the never-colliding search; see '
                         'the module docstring on why this is high')
    for name in ('shoulder-ext-length', 'elbow-ext-length'):
        ap.add_argument(f'--{name}', help='rail length, m')
    for name in ('shoulder-mount', 'elbow-mount'):
        ap.add_argument(f'--{name}', choices=('small', 'big'))
    opts = ap.parse_args()

    if not os.environ.get('ROS_DISTRO'):
        sys.exit('source /opt/ros/jazzy/setup.bash, the mod101 underlay, '
                 'and this workspace first')

    args = mod101_build_args()
    for key in ('shoulder_ext_length', 'elbow_ext_length',
                'shoulder_mount', 'elbow_mount'):
        override = getattr(opts, key, None)
        if override:
            args[key] = override
    print(f'build params: {args}')

    for tool in (opts.tool or TOOLS):
        generate(tool, opts.trials, args)


if __name__ == '__main__':
    main()
